specs:

# GKE istio
- output: 'istio/1.7.3'
  openapi: http://localhost:8001/openapi/v2
  prefix: io.istio.
  patchDir: _custom/istio
  extensionDir: _extensions/istio

# GKE config connector
- output: 'cnrm/1.30.0'
  openapi: http://localhost:8001/openapi/v2
  prefix: com.google.cloud.cnrm.
  patchDir: _custom/cnrm
  extensionDir: _extensions/cnrm
